### ISSUE TITLE
where is the download.sh?

### ISSUE THREAD

**Issue by AmingWu** [XgDuan/WSDEC#13]
Hello,

cd data
sh download.sh

Have you released the download.sh?

**Comment by peterwilson3912** [comment]
Same question. 
Did you run this repo successfully?

**Comment by XgDuan** [comment]
I am very sorry about the missing scripts. Due to my recent update to this repo (to prepare for another paper), some folders and files are changed or missing by my mistake. I will upload the `download.sh' very soon.

**Comment by XgDuan** [comment]
Currently, you can change the repo to the 'nips' tag, within which you could find the `download.sh'. I am considering to change the file structure and set the 'nips' tag as default.

**Comment by peterwilson3912** [comment]
> Currently, you can change the repo to the 'nips' tag, within which you could find the `download.sh'. I am considering to change the file structure and set the 'nips' tag as default.

Hello! Thank you so much for your reply. I don't understand 'nips' tag and I found the download here.
https://github.com/ranjaykrishna/densevid_eval/tree/deba7d7e83012b218a4df888f6c971e21cfeea33

I'm not sure whether it's correct.

**Comment by XgDuan** [comment]
OK, I am working on this now. And your solution is not right. The downloading scripts you find will download the annotation files without downloading the data. I will find a proper way to fix this within one hour.

**Comment by XgDuan** [comment]
Done! I reset the master branch to NIPS version and move all my new changes to another branch. Now it would not cause any confusion.
