### ISSUE TITLE
third_party evaluation script

### ISSUE THREAD

**Issue by XuchenWang** [XgDuan/WSDEC#14]
Hi,

Thank you for sharing your code in such an organized way and it is really helpful! I was trying to run your code and evaluate the result with the provided third-party scripts. However, I encountered an error during the evaluation and I do not know how to fix it. I am wondering did you encountered the same problem while running the evaluate.py provided by the third-party? And if so, how did you solve it? 

Here is the error while I was trying to run the evaluate.py script in the densevid_eval.
![2531591841350_ pic_hd](https://user-images.githubusercontent.com/21342756/84337229-0ad60200-ab67-11ea-80ee-40d7fb7bbfdd.jpg)
Before this, I added 'shell=True' to the subprocess.Popen in both ptbtokenizer.py and meteor.py in order to solve the following two errors:
![2541591841352_ pic_hd](https://user-images.githubusercontent.com/21342756/84337353-57b9d880-ab67-11ea-87de-6e16001052d9.jpg)
![2551591841354_ pic_hd](https://user-images.githubusercontent.com/21342756/84337363-5b4d5f80-ab67-11ea-95be-c33c829d0d43.jpg)

I am not so sure whether my changes to the two files cause the key error, so I am wondering did you also encountered this. Thanks so much in advance:)

**Comment by XgDuan** [comment]
Have you installed JAVA in your machine?

**Comment by XuchenWang** [comment]
No..I see the problem. I did not notice the requirements of COCO Evaluation. But I'm using the python virtual environment. Is there a way to install JAVA under the python virtual environment?

**Comment by XgDuan** [comment]
I think there is something wrong with the evaluation code. Maybe you can raise an issue in their repo: https://github.com/ranjaykrishna/densevid_eval

**Comment by XuchenWang** [comment]
Yeah that's a good idea. Thank you very much!
