### ISSUE TITLE
Question encoundered while reproducing your experiments

### ISSUE THREAD

**Issue by KevinQian97** [XgDuan/WSDEC#15]
Hi! Thanks for releasing your excellent work. 
While reproducing your experiments, I encountered several problems. 
1）Is the default --translator_path should be changed from ./data/translator6000.pkl to ./data/translator.pkl to keep consistent with the dictionary generated in captioning_preprocessing.py? BTW, do I need to change the vocab_size accordingly?
2)  I did not find a download.sh under the folder ./third_party/densevid_eval as stated in the ReadMe. Would u mind give me a hint about how to get that?
Thanks again for releasing. It's really interesting work.

**Comment by KevinQian97** [comment]
When I only change the translator_path to the one I mentioned before and run your example code, I get the assertion error.
The whole log is:
root@bd7e309ada2e:/workspace/WSDEC# python eval_script/evaluate.py --checkpoint /models/final_models/final_model.ckp
[setup, 20]: SET ALL RANDOM SEED 233
[setup, 30]: USE CUDA
./data/translator.pkl
./data/translator.pkl
[test, 20]: ****************************************************************************************************
[test, 20]: process runs on gpu 0
[test, 20]: ****************************************************************************************************
warning: remove test(runs/test) folder
[test, 20]: ****************************************************************************************************
caption generator******************************************************************************************
CaptionGenerator(
  (video_encoder): RNNSeqEncoder(
    (rnn_cell): GRU(500, 512, num_layers=2, batch_first=True, dropout=0.3)
    (linear): Linear(in_features=500, out_features=512)
  )
  (decoder): RNNSeqDecoder(
    (rnn_cell): GRU(2048, 512, num_layers=2, batch_first=True, dropout=0.3)
    (embedding): Embedding(6000, 512)
    (attention_module): AttentionMask(
      (mask_c): ContextMaskC(
      )
      (attention_c): AttentionMean(
      )
      (mask_r): ContextMaskR(
      )
      (attention_r): AttentionMean(
      )
      (mask_l): ContextMaskL(
      )
      (attention_l): AttentionMean(
      )
    )
    (output_layer): Linear(in_features=512, out_features=6000)
  )
)
sentence localizer******************************************************************************************
SentenceLocalizer(
  (video_encoder): RNNSeqEncoder(
    (rnn_cell): GRU(500, 512, num_layers=2, batch_first=True, dropout=0.3)
    (linear): Linear(in_features=500, out_features=512)
  )
  (sent_embedding): Embedding(6000, 512)
  (text_encoder): RNNSeqEncoder(
    (rnn_cell): GRU(512, 512, num_layers=2, batch_first=True, dropout=0.3)
  )
  (feature_mixer): FeatureMixerType0(
    (video_attention): AttentionType0(
      (linear): Linear(in_features=512, out_features=1024)
    )
    (text_attention): AttentionType0(
      (linear): Linear(in_features=512, out_features=1024)
    )
    (text_batch_norm): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True)
    (video_batch_norm): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True)
    (fc): Linear(in_features=1024, out_features=512)
    (combiner): Sequential(
      (0): Linear(in_features=1536, out_features=1536)
      (1): BatchNorm1d(1536, eps=1e-05, momentum=0.1, affine=True)
      (2): ReLU()
      (3): Dropout(p=0.3)
      (4): Linear(in_features=1536, out_features=1536)
      (5): BatchNorm1d(1536, eps=1e-05, momentum=0.1, affine=True)
      (6): ReLU()
    )
  )
  (predictor): Linear(in_features=1536, out_features=15)
  (refiner): Linear(in_features=1536, out_features=30)
)
[test, 20]: ****************************************************************************************************
[test, 30]: use checkpoint: None
[test, 20]: load captioning file, 4917 captioning loaded
[test, 20]: load video feature file, 19994 video feature obj((500,)) loaded
[test, 20]: load translator, total_vocab: 6000
{'grad_clip': 5, 'vocab_size': 6000, 'video_sample_rate': 2, 'translator_path': './data/translator6000.pkl', 'batch_log_interval_test': 20, 'checkpoint_sl': None, 'gpu_id': -1, 'training_epoch': 100, 'optim_method': 'SGD', 'feature_path': './data/anet_v1.3.c3d.hdf5', 'rnn_layer': 2, 'n_rand': 15, 'pe_video': 100, 'attention_type_sl': 'type0', 'soft_mask_function_scale': 1, 'lr_decay_rate': 0.1, 'weight_decay': 0.0001, 'feature_mixer_type': 'type0', 'video_use_residual': True, 'num_workers': 1, 'alter_step': 5, 'checkpoint': None, 'fc_dropout': 0.3, 'lr': 0.01, 'switch_optim_interval': 1, 'caption_loss_mask': 1, 'checkpoint_cg': 'runs/pretrain_cg/cg_pretrain_newloss__00065_10-07-03-02-51.ckp', 'anchor_list': [[0.25, 0.5], [0.5, 0.5], [0.75, 0.5], [0.16666666666666666, 0.3333333333333333], [0.5, 0.3333333333333333], [0.8333333333333334, 0.3333333333333333], [0.0625, 0.125], [0.1875, 0.125], [0.3125, 0.125], [0.4375, 0.125], [0.5625, 0.125], [0.6875, 0.125], [0.8125, 0.125], [0.9375, 0.125], [0.5, 1.0]], 'video_feature_dim': 500, 'pe_sent': 10, 'momentum': 0.8, 'regressor_scale': 0.3, 'attention_type_cg': 'mean', 'save_model_interval': 1, 'reconstruction_loss_mask': 1, 'max_cap_length': 20, 'softmask_scale': 0.1, 'batch_size': 8, 'lr_step': [1, 2, 20], 'sent_embedding_dim': 512, 'pretrain_epoch': 0, 'rand_seed': 233, 'bidirectional': False, 'test_interval': 1, 'lr_decay_step': 5, 'refine_round': 1, 'val_data': './data/densecap/val_1.json', 'rnn_cell': 'gru', 'runs': 'runs', 'iou_thres': 0.9, 'context_type': 'clr', 'batch_log_interval': 10, 'rnn_dropout': 0.3, 'alias': 'final_model_add', 'hidden_dim': 512, 'sent_use_residual': False, 'model': 'CaptionGenerator', 'train_data': './data/densecap/train.json'}
[test, 20]: eval gd model:**************************************************************************************
/workspace/WSDEC/utils/helper_function.py:142: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  linear_transform = torch.range(0, 1, 1.0 / n_rand)[:n_rand].unsqueeze(1)
/workspace/WSDEC/model/networks/seq_encoder.py:62: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greately increasing memory usage. To compact weights again call flatten_parameters().
  output, hidden = self.rnn_cell(input_features[:, i, :].unsqueeze(1), hidden)
Traceback (most recent call last):
  File "eval_script/evaluate.py", line 290, in <module>
    
  File "eval_script/evaluate.py", line 172, in main
    eval(model_sl, model_cg, val_loader, logger, saver, params)
  File "eval_script/evaluate.py", line 83, in eval
    _, sent_pred, sent_len, sent_mask = model_cg.forward(video_feat, video_len, video_mask, ts_seq, ts_gather_idx)
  File "/workspace/WSDEC/model/caption_generator.py", line 50, in forward
    video_feature, video_hidden = self.video_encoder(video_feat)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/WSDEC/model/networks/seq_encoder.py", line 62, in _forward_residual
    output, hidden = self.rnn_cell(input_features[:, i, :].unsqueeze(1), hidden)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 169, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/rnn.py", line 385, in forward
    return func(input, *fargs, **fkwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/function.py", line 328, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/function.py", line 350, in forward
    result = self.forward_extended(*nested_tensors)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/rnn.py", line 294, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/usr/local/lib/python2.7/dist-packages/torch/backends/cudnn/rnn.py", line 258, in forward
    params = get_parameters(fn, handle, w)
  File "/usr/local/lib/python2.7/dist-packages/torch/backends/cudnn/rnn.py", line 165, in get_parameters
    assert filter_dim_a.prod() == filter_dim_a[0]
AssertionError

**Comment by XgDuan** [comment]
Sorry about the confusion, for the first problem, you should change the file name to `translator.pkl'.

I have never met the AssertionError in your second issue ever before. There are some changes in PyTorch standards, which means some API semantics have changed. Would you mind change your PyTorch version to 0.3.1? 

Keep in touch.

**Comment by KevinQian97** [comment]
Hi Xg, thanks for your fast reply. 
Yes, I found it a problem caused by cudnn(7.1) and pytorch(0.4.1) mismatch.
Due to the requirements of GPU card, I can not use pytorch version lower than 0.4.1. So, I manually modified the name of several functions and the shape of output to let it works under PyTorch version 1.0.0. 
Presently, I successfully pass the evaluation procedure. 
Now my remained question is where I can get the official evaluation code. You mentioned in the ReadMe page:
"run the command sh download.sh scripts in the folder PREFIX/WSDEC/third_party/densevid_eval;"
However, I can not find the download.sh scripts under this folder.
I guess I need this to evaluate the quality of generated anchors & captions and make sure my modification does not bring problems.
Thx!

**Comment by XgDuan** [comment]
There should be something wrong when you clone our repo. You can follow the instruction from the following link to construct the evaluation environment:

https://github.com/ranjaykrishna/densevid_eval/tree/deba7d7e83012b218a4df888f6c971e21cfeea33
