### ISSUE TITLE
How long does the training phase of this model take on your device?

### ISSUE THREAD

**Issue by fkxssaa** [XgDuan/WSDEC#2]
Hi, thanks for your helpful code. How many hours does the training phase of this model take on your device?

**Comment by XgDuan** [comment]
The pretraining phase takes about 1 night, and it takes another night to train our final model using a single TITAN X (12G) GPU card. In the final training phase, a majority of time is spent on computing `Meteor` metric calling a Java package.

Also, if you find any problem using our code, pls issue us.
