### ISSUE TITLE
What's the train_script/train_cg_pretrain.py?

### ISSUE THREAD

**Issue by jx-zhong-for-academic-purpose** [XgDuan/WSDEC#3]
In the "training" of your readme, it says "python train_script/train_cg_pretrain.py" first. However, there is no file named "train_cg_pretrain.py" in the "train_script" folder. Which file should we run, "train_cg.py" or "train_captionmodel_pretrain.py"?

**Comment by XgDuan** [comment]
We modified the `readme`. (using `train_captionmodel_pretrain.py`)

Sorry for our mistake when preparing the repo.

**Comment by jx-zhong-for-academic-purpose** [comment]
In this case, https://github.com/XgDuan/WSDEC/blob/11457da5f95dfb3b517b1a5d8f3d3c607f303760/train_script/train_captionmodel_pretrain.py#L171 should be useless.

**Comment by jx-zhong-for-academic-purpose** [comment]
In addition, what is the use of "train_cg.py"?

**Comment by XgDuan** [comment]
Sooooo sorry. I think deleting `exit()` is the correct solution, but I will figure it out carefully later.
For the usage of `train_cg.py`, `train_sl.py`, we have described in `readme.other-usage`.

**Comment by jx-zhong-for-academic-purpose** [comment]
Thx~
