### ISSUE TITLE
Hi! I have some question about just generating caption about full trimmed video

### ISSUE THREAD

**Issue by KiBeomHong** [XgDuan/WSDEC#6]
Hi! 
First, Thank you for your awesome and kindness github!

I'm on research about caption-to-video generation and I need dataset included pair of video and captions.

So This github show me the hope. But I have some problem

I already ready C3D-500dims features via C3D and PCA(n_samples * 1 * 500). But I don't have any video_length and video_mask because i used the trimmed video.

So how can I run just captioning model with your pretrained model?

Thanks you for reading :)

**Comment by XgDuan** [comment]
Thanks for your interests in our code and work. 

I have trained a model for trimmed video captioning (fully supervised, and the results are much better than the weakly-supervised one we provided). But the trained model is not included in this repo.

But I think you can re-train such a trimmed caption generating model using `scripts/train_cg.py`. And you can also re-write an inference method according to `scripts/train_cg.py/eval()` .

You can also email me for more details about the code.
