### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by trahman888** [XgDuan/WSDEC#8]
I have trained supervised video captioning using **train_sl.py**. For evaluating the resultant .ckp which script should I use?

**Comment by XgDuan** [comment]
`train_sl.py` is used to train a "sentence localizer", not "caption generator". But if you still want to eval the performance of "sentence localizing", use`eval_script/eval_sl_gd.py`.

**Comment by trahman888** [comment]
Thanks a lot. That will very helpful for me.
